checkpoint_path: "checkpoints/multi_task_implicit_learner_logistic_gpt_best_config_d128h8B4096_normal_prior/best-model-epoch=96-val_loss=0.22.ckpt"
out_dir: "results/prior_steering_results/gpt_best_config_d128h8B4096_normal_prior"
seed: 0
num_bootstraps: 1

uncertainty:
  mode: "sem"
  band: 1
# Fix the target task and target dataset generation
target_prior:
  mean: 0.0
  std: 1.0

# "Before" prior prefix
base_prior:
  name: "base (mu=0,std=1)"
  mean: 0.0
  std: 1.0

# "After" priors (prior prefix steering)
steered_priors:
  - name: "mu=+1,std=1"
    mean: 1.0
    std: 1.0
  - name: "mu=+2,std=1"
    mean: 2.0
    std: 1.0
  - name: "mu=+3,std=1"
    mean: 3.0
    std: 1.0
  - name: "mu=+4,std=1"
    mean: 4.0
    std: 1.0
  - name: "mu=+5,std=1"
    mean: 5.0
    std: 1.0
  - name: "mu=+6,std=1"
    mean: 6.0
    std: 1.0
  - name: "mu=+7,std=1"
    mean: 7.0
    std: 1.0
  - name: "mu=+8,std=1"
    mean: 8.0
    std: 1.0

data:
  x_dim: 8
  num_prior_tasks: 20
  sequence_length: 50
  context_len: 5
  num_query_points: 10000

  noise_std: 0.0
  x_mean: 0.0
  x_std: 1.0
